####################
### WINDOW RULES ###
####################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for window rules

# Example windowrule
# windowrule = float,match:class ^(kitty)$,match:title ^(kitty)$

# "Smart gaps" / "No gaps when only"
workspace = w[tv1], gapsout:1, gapsin:0
workspace = f[1], gapsout:1, gapsin:0
windowrule = border_size 1, float off, match:workspace w[tv1]
windowrule = rounding 0, float off, match:workspace w[tv1]
windowrule = border_color $sky, float off, match:workspace w[tv1]
windowrule = border_size 1, float off, match:workspace f[1]
windowrule = rounding 0, float off, match:workspace f[1]
windowrule = border_color $sky, float off, match:workspace f[1]

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on,match:class ^$,match:title ^$,match:xwayland 1,float on,match:fullscreen 0,match:pin 0

# Override opacity for active, inactive, fullscreen windows
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class firefox
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class mpv
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class feh
windowrule = opacity 1.0 override 1.0 override 1.0 override, float on

##### Floating Windows #####
windowrule = border_color $sky, float on

# WiVRn Settings
windowrule = float on, match:class io.github.wivrn.wivrn
windowrule = center on, match:class io.github.wivrn.wivrn
windowrule = size 50% 70%, match:title Settings — Strawberry Music Player

# Bluetooth Manager
windowrule = float on, match:class .blueman-manager-wrapped
windowrule = center on, match:class .blueman-manager-wrapped
windowrule = size 50% 70%, match:class .blueman-manager-wrapped

# Network Manager
windowrule = float on, match:class nm-connection-editor
windowrule = center on, match:class nm-connection-editor
windowrule = size 50% 70%, match:class nm-connection-editor

# Waybar Menus
windowrule = float on, match:class float_waybar
windowrule = center on, match:class float_waybar
windowrule = size 50% 70%, match:class float_waybar

# Pavucontrol settings
windowrule = float on, match:title Volume Control
windowrule = center on, match:title Volume Control
windowrule = size 50% 70%, match:title Volume Control

# Kvantum Manager
windowrule = float on, match:title Kvantum Manager
windowrule = center on, match:title Kvantum Manager
windowrule = size 50% 70%, match:title Kvantum Manager

# QT5 Settings
windowrule = float on, match:class qt5ct
windowrule = center on, match:class qt5ct
windowrule = size 50% 70%, match:class qt5ct

# QT6 Settings
windowrule = float on, match:class qt6ct
windowrule = center on, match:class qt6ct
windowrule = size 50% 70%, match:class qt6ct

# GTK Settings
windowrule = float on, match:class nwg-look
windowrule = center on, match:class nwg-look
windowrule = size 50% 70%, match:class nwg-look

# solaar
windowrule = float on, match:class solaar
windowrule = center on, match:class solaar
windowrule = size 50% 70%, match:class solaar
